### ISSUE TITLE
Add gulp task to make it easy for this sample to run web server

### ISSUE THREAD

**Issue by jthake** [OfficeDev/outlook-add-in-command-demo#1]
Like the Yeoman generator...would be great if you could run a gulp task to run up a web server in command prompt. e.g. npm install, then "gulp serve-static".
Essentially need to put the gulpfile.js and a package.json.

I have this already done if you want it?

**Comment by jasonjoh** [comment]
Thanks man, sorry it took so long to get to this. I'm merging the PR now.

**Comment by jasonjoh** [comment]
Merged
