### ISSUE TITLE
Function button doesn't work in Outlook 2016 desktop

### ISSUE THREAD

**Issue by mganss** [OfficeDev/outlook-add-in-command-demo#10]
When I click the function button nothing gets inserted, only a throbber appears above the "Send" button with a message saying "Add-in Command Demo is working on your Insert default message request".

**Comment by jasonjoh** [comment]
Sorry to hear! This can happen for a number of reasons, but most commonly will happen if the code being executed hits an exception and fails to call `event.completed()`. Which button are you clicking to reproduce this, and have you modified the code at all?

**Comment by mganss** [comment]
The "Insert default message" button. I have not modified the code, simply cloned the repo and ran `gulp serve-static`.

Before testing with this demo project, I had also tried creating a new add-in project from within VS. This resulted in the same behavior, even when the function was directly in a `<script>` section in the head of the function file and did nothing but call `event.completed()`.

**Comment by jasonjoh** [comment]
Ah. I wonder if this is a problem with the SSL certificate used by the gulp web server. Can you open https://localhost:8443/AppCompose/Home/Home.html in a browser and see if you have any certificate trust warnings?

**Comment by jasonjoh** [comment]
Just wanted to check if you were able to look into the SSL thing.

**Comment by mganss** [comment]
Sorry, I won't have time to check this until April 25.

**Comment by jasonjoh** [comment]
No problem, just didn't want to leave you hanging.

**Comment by mganss** [comment]
Yes, I get a certificate trust warning. However, I have successfully built a custom pane Outlook add-in based off the VS project template which runs locally in IIS Express (port 44300). I have also tried creating a command add-in project from VS but the behavior is the same.

**Comment by jasonjoh** [comment]
Outlook disables scripts and such if the cert isn't trusted. You'll need to trust the cert that the gulp-webserver uses: https://github.com/OfficeDev/generator-office/blob/master/docs/trust-self-signed-cert.md

**Comment by mganss** [comment]
That solved it. Thanks.
