### ISSUE TITLE
Outlook.Com under Manage Add-Ins I Don't See A Plus

### ISSUE THREAD

**Issue by DavidJSnyder** [OfficeDev/outlook-add-in-command-demo#11]
I'm following instructions to try from an Outlook.Com account. When I go to Manage Add-Ins I don't see a toolbar with a + on it to select Add From File, instead only a list of Add-Ins from the Store.  Is that part of the instructions out of date?  If Outlook.com has disabled the Add From File functionality what's a good alternative for testing in development?
![manage add-ins](https://cloud.githubusercontent.com/assets/8460494/14322592/7450b99e-fbeb-11e5-93eb-4b082910ef88.png)

**Comment by jasonjoh** [comment]
Hmm. That looks like the Add-in store in desktop Outlook. Did you logon to your Outlook.com account in your browser? The add from file functionality is only available in the web client.

**Comment by DavidJSnyder** [comment]
It's part of a screenshot from IE 11 going to Outlook.com on a Windows 7 machine.  It also looks like that in Chrome.

![chrome](https://cloud.githubusercontent.com/assets/8460494/14387517/cb7dcc56-fd77-11e5-8a93-f0f16fb94b61.png)

**Comment by jasonjoh** [comment]
Ah ok. Let me check with the folks who manage this. None of my accounts have this UI, so let me see what's going on :)

**Comment by jasonjoh** [comment]
Ok. It looks like your account has gotten the new in-client store that's rolling out. You should be able to get to the right place by clicking the gear, going to **Options**. Then in the left-hand nav expand **General**, and click **Manage add-ins**.

![image](https://cloud.githubusercontent.com/assets/8966342/14390813/eef4777a-fd86-11e5-8e6a-959efc29790c.png)

Let me know if that works and I'll update the instructions.

**Comment by DavidJSnyder** [comment]
Yes, that works, thanks.
