### ISSUE TITLE
Show task pane by javascript

### ISSUE THREAD

**Issue by jmk09** [OfficeDev/outlook-add-in-command-demo#12]
Is it possible to show the task pane by Javascript? I know it's possible to show the task pane with a button through the manifest file (`<Action xsi:type="ShowTaskpane">`) but I'm looking for the following:
1. User executes a function by pressing a button (`<Action xsi:type="ExecuteFunction">`).
2. The functionFile checks for a condition, in our case check if a certain roamingSetting is set.
3. If not, the task pane is shown to ask a user to store the needed roamingSetting.

If this is not possible:
- Is it possible to check for a First Run?

**Comment by jasonjoh** [comment]
No, you can't do a taskpane by Javascript. However, you could show a dialog using the new [dialog API](http://dev.office.com/reference/add-ins/shared/officeui).
