### ISSUE TITLE
Error when attempting to use localhost

### ISSUE THREAD

**Issue by richorama** [OfficeDev/outlook-add-in-command-demo#13]
Hi,

When I followed the instructions, I get a `net::ERR_INSECURE_RESPONSE` as the browser doesn't trust the self signed cert.

To get around this I visited the site directly in the browser, and chose to trust the cert, as described here:

http://stackoverflow.com/questions/23688565/failed-to-load-resource-neterr-insecure-response

Perhaps the readme could be updated to include this step?

**Comment by jasonjoh** [comment]
Thanks for the suggestion! I'll add that shortly.
