### ISSUE TITLE
Outlook 2016 on Mac

### ISSUE THREAD

**Issue by ghost** [OfficeDev/outlook-add-in-command-demo#14]
Hi Jason, 

Awesome work; keep it up. I just wanted to let you know that your add-in doesn't work on Outlook 2016 on a Mac. Do you have any idea why it doesn't work? 

Here's a screenshot
![image](https://cloud.githubusercontent.com/assets/1163664/16341422/ea19a9ae-39fa-11e6-83ec-1750702e18be.png)

I'm using Outlook Version 15.23 (160611) on OS X El Captain v10.11.5

**Comment by jasonjoh** [comment]
Thanks Andrew! I'm not aware of a problem there, but I'll take a look and see if I can reproduce it.

**Comment by ghost** [comment]
Thanks @jasonjoh. Much appreciated. Let me know if you need help testing or have any questions/concerns.

**Comment by jasonjoh** [comment]
I just tried it on an earlier version of Outlook (15.22). It worked fine there. I'm going to update and see if I can reproduce.

**Comment by jasonjoh** [comment]
I cannot reproduce this behavior. I've updated to the same version and it works fine for me. Visually it looks like TaskPane.js isn't loading or executing, maybe start by verifying TaskPane.js is reachable?

**Comment by jasonjoh** [comment]
Andrew, did you ever figure this out?

**Comment by ghost** [comment]
This is so weird, your demo works on my mac now. I don't know what fixed it and I don't know how to reproduce this bug.

Sorry @jasonjoh for the late reply.

**Comment by ghost** [comment]
Thanks for your help @jasonjoh!
