### ISSUE TITLE
Changing Icons?

### ISSUE THREAD

**Issue by vgogov** [OfficeDev/outlook-add-in-command-demo#15]
I got the add-in to work. But when I edit the Icon colours (ie. in paint, replace the blue  with yellow etc.) and keep the same filename and reinstall the add-in, the icons still stays blue. On the gulp server the icons are yellow, in the 'Images' folder they are yellow. So where is Office getting the blue icons, even after reinstalling the add-in when none exist?

**Comment by vgogov** [comment]
Fixed it. It was due to a caching issue.

**Comment by jasonjoh** [comment]
Glad to see you figured this out. Just to add some additional info:

Icons are cached here locally (for Outlook 2016 on Windows):

%localappdata%\microsoft\office\16.0\wef\Resources

Older versions of 2016 may have the cache here instead:

%localappdata%\microsoft\office\16.0\wef\icons
