### ISSUE TITLE
Icons over https://localhost

### ISSUE THREAD

**Issue by AmanpreetSingh-GitHub** [OfficeDev/outlook-add-in-command-demo#17]
Icons are not visible in Outlook 2016 desktop when we have deployed the demo on localhost over https protocol, thou they are visible in Outlook Web App.

**Comment by jasonjoh** [comment]
I don't reproduce this. Did you trust the SSL certificate you have setup for localhost?

**Comment by AmanpreetSingh-GitHub** [comment]
I think thats the issue. I did not setup SSL certificate for localhost.
