### ISSUE TITLE
Can't install addin

### ISSUE THREAD

**Issue by tigerxy** [OfficeDev/outlook-add-in-command-demo#18]
Server is running, but when I try to install addin, I get the following message:

> ## Das hat leider nicht geklappt.
> 
> Diese App kann nicht installiert werden. Diese App wird von der Version von Exchange Server, mit der Ihr Konto eine Verbindung herstellt, nicht unterstützt.

**Comment by jasonjoh** [comment]
It looks like you're installing this on your company's internal Exchange server (or your own private testing server)? What version of Exchange?

**Comment by jasonjoh** [comment]
If you still need help please reopen.
