### ISSUE TITLE
Doesn't support 'éèà' characters

### ISSUE THREAD

**Issue by sybic2001** [OfficeDev/outlook-add-in-command-demo#19]
Hi, i succesfully installed and configured the add-in. There is a big issue for me : as soon as i add a special character (é è à or other...) in any string of characters of the manifest, I get an "invalid character in the given encoding" error when I submit the manifest file.

The encoding is specified to be in UTF-8. I edit the manifest with Sublime Text 3, specifying to save in UTF-8. I tried with and without BOM. But still not working. I don't understand the reasons of such a problem !

**Comment by jasonjoh** [comment]
I don't reproduce this. Can you give me more details on what exactly you're doing?
- What string are you modifying in the manifest?
- Are you installing this on Office 365 or a private/corporate Exchange server? If Exchange server, what version?

**Comment by sybic2001** [comment]
For example with : Description DefaultValue=""

I just figured out a way to handle it : i changed encoding in the first
line to ISO-8859-1. And now it accepts all characters. Sounds really
mysterious ! It means that it might come from Sublime Text editor ?

I am using Office 365 Business.

Thanks for your support !

2016-11-03 13:32 GMT+01:00 Jason Johnston notifications@github.com:

**Comment by jasonjoh** [comment]
I'm using Visual Studio code, and just added a 'é' character. I had done it to another property, but to be sure, I just added it to the `Description` and I have no issue. When it fails for you, is it failing at install time? What error does it give?

**Comment by sybic2001** [comment]
I upload the manifest online through the parameters of my outlook account.

[image: Images intégrées 1]

2016-11-03 13:41 GMT+01:00 Jason Johnston notifications@github.com:

**Comment by jasonjoh** [comment]
Did you mean to include an image? It didn't take :)

**Comment by sybic2001** [comment]
here it is

2016-11-03 14:28 GMT+01:00 Jason Johnston notifications@github.com:

**Comment by jasonjoh** [comment]
@sybic2001 Sorry for not following up sooner, but again your image didn't come through. It sounds like you worked around the problem so I'm closing this for now. If you still need help please reopen.
