### ISSUE TITLE
Addin in Mac

### ISSUE THREAD

**Issue by anujkumar-df** [OfficeDev/outlook-add-in-command-demo#20]
Hi,

I have installed this addin in my office 365 account.

When I open my account in Windows Outlook 2016, I can see icons in header toolbar. But those icons don't appear on Mac Outlook 2016. Though I can see it working when I open the mail item. Is this not supported on mac ?

Thanks.

**Comment by jasonjoh** [comment]
Not yet. Add-in commands are coming to Mac soon though.

**Comment by jasonjoh** [comment]
@anujkumaraurea If you are in the Office Insider program (in Microsoft AutoUpdate on your Mac) and you've chosen the "Office Insider Fast" builds, commands are in the latest update!

**Comment by anujkumar-df** [comment]
@jasonjoh How can I check the stability of the build, I think it still needs time to be production ready, right ?

**Comment by jasonjoh** [comment]
Yes, it's likely not something you want to deploy in "production" to a vast user base. It's more akin to dev builds, intended for developers to test with or enthusiasts to get a hold of the latest stuff early and provide feedback.

**Comment by anujkumar-df** [comment]
@jasonjoh Do you have any release date or plan, when you intend to push experimental features into main build ?

**Comment by jasonjoh** [comment]
For Mac Outlook you mean? I don't believe the team has a public roadmap unfortunately. You could follow @OfficeInsider on Twitter for announcements.
