### ISSUE TITLE
Command addin dont load on outlook starup

### ISSUE THREAD

**Issue by anujkumar-df** [OfficeDev/outlook-add-in-command-demo#21]
Hi,

I checked command addin demo for outlook 2016 on mac. It seems addin don't load on outlook startup, but as soon as I try to compose a new email, they start showing on mail window as well as on main outlook toolbar. I suppose this is not the desired behavior.

**Comment by jasonjoh** [comment]
In order for it to show you must have a message or appointment selected. You don't need to compose, reading a message would do it. Is that not what you see?

**Comment by anujkumar-df** [comment]
Nopes, when I open outlook, and an email is preselected, button are not visible.

As soon I double click one of them, they start showing on ribbon of both windows, email window as well as outlook window.

**Comment by jasonjoh** [comment]
I don't reproduce that behavior. Not sure if it makes a difference but I have the reading pane turned on, set to "Right".

In any event it's not a problem with the add-in, so closing this issue. If you'd like to provide feedback to the Mac Outlook team regarding the behavior, use the "Suggest a Feature" option on the Help menu.
