### ISSUE TITLE
How to test during development?

### ISSUE THREAD

**Issue by abhilash-im** [OfficeDev/outlook-add-in-command-demo#23]
In pre-requisites, it is mentioned that the sample needs to be hosted in HTTPS website. What are the requirements for development using Visual Studio? Is it possible to debug the app within Visual Studio by simply pressing F5? Does that work?

Any help will be appreciated.
Thanks.

**Comment by jasonjoh** [comment]
This sample does not have any Visual Studio project file, so you can't just hit F5. Visual Studio does have an Office Add-in project type, so you could recreate this in Visual Studio and get that ability.

Another option I've used successfully is Node.js with the [http-server package](https://www.npmjs.com/package/http-server), so you can quickly run a test server from the command line.
