### ISSUE TITLE
gulp task `validate-xml` is missing manifest.xsd

### ISSUE THREAD

**Issue by schmkr** [OfficeDev/outlook-add-in-command-demo#25]
The gulp task to validate if your manifest xml is valid, seems like a very useful utility. When trying to run it though, it is looking for a local xsd file, but that is not in this repository. Can you add `manifest.xsd` to this project? Or add the link to the README?

**Comment by jasonjoh** [comment]
I believe you used to get it if you used older versions of the [Office Add-in Yeoman Generator](https://github.com/OfficeDev/generator-office) to create a project. This project was originally created that way. Newer versions of the generator have removed this stuff, we're investigating creating a standalone validator.

[manifest.zip](https://github.com/jasonjoh/command-demo/files/875986/manifest.zip)
