### ISSUE TITLE
HTML output of email is empty in Outlook for Android 

### ISSUE THREAD

**Issue by abhishek1234321** [OfficeDev/outlook-add-in-command-demo#27]
I installed the add-in in my outlook.com account, hosted on a https nginx server, with CORS enabled.
When I click on the Display all properties, the body(HTML) is different in android

### Outlook on Android
![android](https://user-images.githubusercontent.com/529159/30894110-5f92e546-a35f-11e7-8a65-a81493ada79c.png)

### Outlook for iOS
![image](https://user-images.githubusercontent.com/529159/30900749-bfe064c8-a382-11e7-9fdc-7b17124802f6.png)

### Outlook Web
![screen shot 2017-09-27 at 8 38 07 am](https://user-images.githubusercontent.com/529159/30894122-778062b4-a35f-11e7-9ca4-ce298943c5e7.png)

### Outlook for Mac
![screen shot 2017-09-27 at 10 07 09 am](https://user-images.githubusercontent.com/529159/30896014-ab719bae-a36b-11e7-9972-d51a913de2c9.png)

The email was forwarded from Gmail. When I remove the "From: blah blah blah" from the body of the email and forward, it works fine.

Has someone encountered this? Anything that can be done to fix this?

**Comment by abhishek1234321** [comment]
Added iOS screenshot

**Comment by jasonjoh** [comment]
Does the body display OK (outside of add-ins) in Outlook on Android? I haven't seen this.

**Comment by abhishek1234321** [comment]
Yes, it does. Do you want me to put screenshots?

**Comment by jasonjoh** [comment]
No that's OK. I'm at Ignite this week but can look at this when I return. Are you able to reproduce with any message forwarded from GMail, or is it just this particular one?

**Comment by abhishek1234321** [comment]
Sure, thanks. 

All messages forwarded from Gmail. This happens with messages forwarded from Yahoo too. 

Anything I can do to figure out what the issue is?

**Comment by jasonjoh** [comment]
I suspect a bug in Outlook for Android since it works everywhere else. In that case I'm not sure there is anything you can do! It would be interesting to see if this reproduces in another add-in like Translator (which I believe is available on Android). If it shows just an empty body that would indicate it's a larger issue than just this sample.

**Comment by abhishek1234321** [comment]
Is there a way I can check if the body is empty for translator plugin (https://appsource.microsoft.com/en-us/product/office/wa104380627?src=office&corrid=8ed6f226-4499-4ace-bea2-9d6934867e44&omexanonuid=df70fb5e-c7e4-4740-b11b-bfef1058c45e)? because the plugin seems to work fine in Android, it could be that that the actual translated display and the `getAsync` call behave differently?

**Comment by jasonjoh** [comment]
Well I'm making a lot of assumptions about the Translator add-in, but the only way an add-in can get the body is with `getAsync`.

**Comment by abhishek1234321** [comment]
If only there was a way to check this :) Do let me know once you look into it.

**Comment by abhishek1234321** [comment]
any updates on this?

**Comment by jasonjoh** [comment]
I finally got my hands on an Android device to test this, and I reproduce it. That gives us something to investigate here.

**Comment by abhishek1234321** [comment]
That's reassuring :) waiting for more details, thank you.

**Comment by abhishek1234321** [comment]
It doesn't work with Connected accounts as well, I connect Gmail to check if the problem was only with forwarded emails.

This time the body (HTML) and body (Text) is just empty.

### Android
![screenshot_20171003-123918](https://user-images.githubusercontent.com/529159/31113702-22586092-a838-11e7-98f2-c61c405678be.jpg)

### iOS
![unknown](https://user-images.githubusercontent.com/529159/31114229-a1f0204a-a83a-11e7-9ab6-36456db6872a.jpeg)

### Outlook for mac
![screen shot 2017-10-03 at 12 57 24 pm](https://user-images.githubusercontent.com/529159/31114205-8939056c-a83a-11e7-9f5c-1f6a3263f20a.png)

### OWA
![screen shot 2017-10-03 at 12 40 06 pm](https://user-images.githubusercontent.com/529159/31113823-d1215a20-a838-11e7-886a-5c2be696ff0d.png)

The dateTimeCreated and dateTimeModified is also different.

**Comment by abhishek1234321** [comment]
any update or any workaround to get this working? If the translator plugin works then there should be a workaround is my guess.

**Comment by jasonjoh** [comment]
It looks like a bug, the devs are checking. Translator is working because it actually uses the REST API to get the body of the message instead of doing `body.getAsync`.

**Comment by abhishek1234321** [comment]
hey, any update on this? I did see many outlook app updates going out for Android in the last couple of weeks

**Comment by abhishek1234321** [comment]
This is fixed I guess, can be closed.
