### ISSUE TITLE
i installed add-in command demo but unable to use it.It displays error while using in mail

### ISSUE THREAD

**Issue by chgowthami** [OfficeDev/outlook-add-in-command-demo#28]

**Comment by abhishek1234321** [comment]
What error do you get when you try to install? I was able to get it running just fine

**Comment by jasonjoh** [comment]
@chgowthami can you elaborate? I'm assuming that you've either uploaded the files to a web server or you're running the `gulp webserver` task to serve the files from localhost.

If you uploaded to a web server, make sure you've updated the manifest URLs to point to the new server.

If you are running from localhost, make sure that you trust the localhost certificate and you can browse to the add-in (open your browser and go to `https://localhost:8443/AllPropsView/AllProps.html`)

**Comment by chgowthami** [comment]
i get an error as
"We're sorry, we couldn't access Add-in Command Demo. Make sure you have a network connection. If the problem continues, please try again later."

**Comment by abhishek1234321** [comment]
where are you trying to run this from? where the is the outlook-add-in hosted? Is it locally or on a server?

**Comment by chgowthami** [comment]
Hosted on localhost .Add-in added to mail compose page and i am trying to run at mail compose..

**Comment by abhishek1234321** [comment]
I got it working pretty well on all devices.
