### ISSUE TITLE
Outlook add-in REST API support

### ISSUE THREAD

**Issue by abhishek1234321** [OfficeDev/outlook-add-in-command-demo#29]
Is REST API support available in Android and iOS outlook client? (Using Office.js)

I wish to read the attachments using my outlook add-in, since `Office.context.mailbox.ewsUrl` is not supported in mobile, I used [REST API](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api)  to get the base64 encoding of the attachment.

I use `Office.context.requirements.isSetSupported('Mailbox', '1.5')` to get the attachments.
This works well in OWA in the browser. But when I check for this in Outlook for Android, it is returned as `false`. I debugged using Vorlon JS and this is the output I got

OWA Browser
![owa](https://user-images.githubusercontent.com/529159/34666188-156542ea-f489-11e7-93e9-3c5b5d8d5a99.png)

Outlook Mobile App (Android)
![outlook-android](https://user-images.githubusercontent.com/529159/34666255-6942c414-f489-11e7-852b-11f0f25a3042.png)

If I do not check specifically for `Office.context.requirements.isSetSupported('Mailbox', '1.5')` this and use the `Office.context.mailbox.restUrl + '/v2.0/me/messages/' + itemId + '/attachments'` directly, it works fine on OWA in browser and Outlook for Android.

What is the minimum version of `Mailbox` with which the REST API works? (Because I got it working with `Mailbox 1.4` in Android?

As per the docs, it says this feature is in `Preview`, but I see there is a `1.5` version of docs and a `Preview` version of docs.
![screen shot 2018-01-08 at 3 41 51 pm](https://user-images.githubusercontent.com/529159/34666446-78a204f0-f48a-11e7-9dce-813c2ebe80f1.png)

Also, how does one check what version of `Mailbox` is supported by different clients?

Any help is appreciated.

Thanks

**Comment by jasonjoh** [comment]
Ok so it's a little confusing :). 1.5 introduces the new signature to `getCallbackTokenAsync` which includes the `isRest` parameter. This is needed in OWA/Desktop to get a REST-compatible token. In mobile, the token is always REST-compatible, so you can use the old `getCallbackTokenAsync` from 1.4.

https://dev.office.com/reference/add-ins/outlook/tutorial-api-requirement-sets?product=outlook&version=v1.5#clients lists the current requirement set levels for our clients.

Thanks for pointing out the doc issue stating it's in preview. I've logged https://github.com/OfficeDev/outlook-dev-docs/issues/138 to address.

**Comment by abhishek1234321** [comment]
ok that does help.

I have another question, I wish to test the add-in on Outlook 2013, I have a windows dev account, but the download for 2013 is no longer available.

Is there a way to get this working?

Thanks

**Comment by abhishek1234321** [comment]
Anything on this?

**Comment by jasonjoh** [comment]
Sorry! Didn't see this one. So Outlook 2013 won't support getting a REST token as it only supports up to requirement set 1.3. That being said you can still of course test the add-in on 2013. If you have an MSDN subscription you can download Office 2013 from there.

**Comment by abhishek1234321** [comment]
So I do have a MSDN account and I tried downloading from here https://portal.office.com/OLS/MySoftware.aspx?source=ohp-ib

![screen shot 2018-01-19 at 11 36 16 pm](https://user-images.githubusercontent.com/529159/35164715-8e931b06-fd71-11e7-980c-c160ec2d81db.png)

There was an option to download 2013 before, but I no longer see it.

Also, is there a way to run both 2013 and 2016 in Windows? It is quite painful to uninstall and reinstall just to test.

**Comment by jasonjoh** [comment]
MDSN downloads are separate from the Office portal download. That's for the current "click-to-run" Office 365 builds, so it's not surprising that 2013 isn't on there :).

For MSDN, you need to go to the "Subscriber Portal" (upper right-hand link on the MSDN home page). Then click the "Downloads" nav on the top and you should see Office 2013 on the download page.
![image](https://user-images.githubusercontent.com/8966342/35172165-87faeca2-fd34-11e7-933e-036be16cff40.png)

AFAIK there isn't a way to have both Office 2013 and 2016 on the same machine.

**Comment by abhishek1234321** [comment]
I do not see the option to download Office 2013, on the Downloads page.
![screen shot 2018-02-01 at 11 32 04 pm](https://user-images.githubusercontent.com/529159/35694743-4271341a-07a8-11e8-8efd-fd1ce48f1ddc.png)

When I search for Office 2013, I get 4 options to download from.
![screen shot 2018-02-01 at 11 32 22 pm](https://user-images.githubusercontent.com/529159/35694880-bbec06a8-07a8-11e8-9b6c-5bef33d109e1.png)

All 4 of them don't work. I get the following error.
![screen shot 2018-02-01 at 11 35 27 pm](https://user-images.githubusercontent.com/529159/35694842-9e10a21a-07a8-11e8-8626-d81d2c48490f.png)

This on Windows Server 2012.

**Comment by jasonjoh** [comment]
Sorry to hear that. You should contact MSDN support for help with that. I've tried to help as best I could, but this repository isn't the appropriate place to troubleshoot MSDN downloads :)

**Comment by abhishek1234321** [comment]
Alright. Thanks for the support.
