### ISSUE TITLE
Add-in doesn't work on mobile 

### ISSUE THREAD

**Issue by StephanieNadia** [OfficeDev/outlook-add-in-command-demo#32]
Hello,

I followed your tutorial step by step but I have a problem: the add-in appears on mobile but it doesn't work.

The node js server is started on my computer. I don't know if it is because my add-in is accessible by localhost. If it is that the issue, please tell me how to make it accessible remotely.

 Thank you.

**Comment by jasonjoh** [comment]
Yes, when you run it locally, it is only accessible by clients on that machine. So you could use Outlook or Outlook on the web, but your mobile client would have no way to reach it.

In order for it to work on your mobile device, you need to deploy it to a real web server.

**Comment by StephanieNadia** [comment]
Thank you for your answers.
