### ISSUE TITLE
add-in doesn't work when sideloaded with URL

### ISSUE THREAD

**Issue by StephanieNadia** [OfficeDev/outlook-add-in-command-demo#33]
My add-in is accessible from my web server azure. But it doesn't work. The taskpane opens but when I click on the button to send the email it doesn't do anything. the error that appears in the console of google chrome is : 

Uncaught Error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.
    at office.debug.js:1496
    at validateFunction (office.debug.js:281)

Thank you.

**Comment by jasonjoh** [comment]
Is this custom code you've added? I'm fairly confident I don't load office.debug.js at all in this project. Which taskpane are you referring to, and which button?
