### ISSUE TITLE
Task Pane fails to re-initialize when switching between Read and Compose modes

### ISSUE THREAD

**Issue by addisondavid** [OfficeDev/outlook-add-in-command-demo#34]
In production, we've noticed the following when toggling between reading and composing messages where, it appears, due to the app not re-initializing as expected, the expected `Office.context.mailbox.item` fails to properly load.

I've forked this repo and created the following branch with the additional code needed to reproduce the issue: https://github.com/addisondavid/outlook-add-in-command-demo/tree/office-initialize-failure

**Prerequisite**: the task pane should already be pinned in read mode.

On outlook.office.com, do the following:
1. Click the `Inbox` folder
2. Click the first message in the Inbox folder
**Expected Result**: The pinned task pane in read-mode appears displaying the appropriate mailbox context item (i.e. the currently selected message)
**Actual Result**: Performs as expected
_Note_: Office.initialize was called

From here, do the following:
1. Click `New`
**Expected**: The pinned task pane in compose-mode appears displaying the appropriate mailbox context item (i.e. the current state of the composed message)
**Actual**: Performs as expected
_Note_: Office.initialize was called

From here, do the following:
1. Discard the new message, returning to the previously selected message in the Inbox folder
2. Click the `Add-In Command Demo` icon
3. Click the `Open Task Pane` menu item
**Expected**: The pinned task pane in read-mode appears displaying the appropriate mailbox context item (i.e. the current state of the composed message)
**Actual**: Performs as expected
_Note_: Office.initialize was called

From here, do the following:
1. Click `New`
**Expected**: The pinned task pane in compose-mode appears displaying the appropriate mailbox context item (i.e. the current state of the composed message)
**Actual**: The pinned task remains in read-mode, opened to the previously selected mailbox item and not the compose-mode state, displaying the current state of the composed message.
_Note_: Office.initialize was not called

This issue occurs when the task pane is pinned in the read mode and regardless of whether previously pinned in compose mode or during the first `Click New` step.

Is this indeed a bug, or have I missed a step?

**Comment by jasonjoh** [comment]
My understanding is that pinnable task panes are only supported for read forms, so I would expect it to work this way. I actually would NOT expect the 2nd result that you're reporting there.

@wamaina can you confirm?

**Comment by exextoc** [comment]
Pinnable task panes are available in both compose and read scenarios. 
Thank you for reporting this issue. We are working on a fix as quickly as we can.

**Comment by jasonjoh** [comment]
Closing this issue since this seems to be a bug outside of my control.
