### ISSUE TITLE
Iframed dialog fails to open from pinned task bar when listening for ItemChanged event.

### ISSUE THREAD

**Issue by addisondavid** [OfficeDev/outlook-add-in-command-demo#35]
In production, we've run into an issue where an iframed dialog in a web client (e.g. Chrome) will initially open successfully when triggered from the task pane. However, subsequent requests unexpectedly fail when initiated as follows:

At outlook.office.com, do the following:
1. Click the `Inbox` folder
2. Click the first message in the Inbox folder
3. If the task pane wasn't previously pinned
   1. Click the `Add-In Command Demo` icon
   2. Click the `Open Task Pane` menu item
4. In the Task Pane, click the `Open iDialog` button to open an iframed dialog window
**Expected**: The dialog should simply appear
**Actual**: Performs as expected
_Note_: `document.querySelector('iframe[id$=":Dialog"]').id` confirms a successful DOM query of the dialog.

From here, do the following:
1. Ensure the Task Pane is pinned (i.e. the pin icon is pointing downward)
2. Close the current dialog
3. Click a different message in the Inbox folder
4. In the Task Pane, click the `Open iDialog` button to open an iframed dialog window
**Expected**: The dialog should simply appear
**Actual**: The dialog doesn't appear even though the response from the Dialog API suggests it was indeed opened. Further attempts to open the dialog are unsuccessful as the api errors with: _"A dialog is already opened"_.
_Note_: `document.querySelector('iframe[id$=":Dialog"]').id` fails to find the element the API suggests is present.

Is there a current fix or workaround for this?

I've forked this repo, created the following branch: https://github.com/addisondavid/outlook-add-in-command-demo/tree/office-initialize-failure, implemented the simple dialog web example found here: https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example and added the additional code needed to reproduce the issue.

There is a workaround (I can't find the link to the article atm) that suggests calling the close method is a try/catch block to force/ensure it's closed but this did not work.

**Comment by addisondavid** [comment]
Update: I could have sworn I had searched SO for the appropriate solution and found nothing but here it is, now that I've begun writing out the SO question, the appropriate solution has been found: https://stackoverflow.com/questions/51412193/outlook-add-in-trouble-opening-dialogs-from-pinnable-taskpane :)

**Comment by jasonjoh** [comment]
Great! Closing this issue then :)
