### ISSUE TITLE
Add-in doesn't appear in action items tab

### ISSUE THREAD

**Issue by twix20** [OfficeDev/outlook-add-in-command-demo#36]
Hi, i cloned and run the repo, added manifest to outlook web but the Add-in doesn't show up in the "Action Items" tab like in the Readme picture with a yellow arrow. 

Do i have to make any adjustments to display add-in inside that tab?

Thanks in advance.

[Issue preview](https://i.imgur.com/T38GKPt.png)

**Comment by jasonjoh** [comment]
The *Action Items* button you're showing there is the old style of add-in integration. That style is no longer supported, but there are still some old legacy add-ins that use it.

Add-ins now appear near the top of the message UI as you show in your screenshot.
