### ISSUE TITLE
npm install fails, gnome git.gnome.org decomissioned

### ISSUE THREAD

**Issue by butchmarshall** [OfficeDev/outlook-add-in-command-demo#37]
npm install fails

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! warning: templates not found /tmp/pacote-git-template-tmp/git-clone-ce68d33a
npm ERR! fatal: unable to connect to git.gnome.org:
npm ERR! git.gnome.org[0: 209.132.180.180]: errno=No route to host
npm ERR! git.gnome.org[1: 209.132.180.168]: errno=No route to host
npm ERR! 
npm ERR! fatal: clone of 'git://git.gnome.org/libxml2' into submodule path 'libxml2' failed
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/butch/.npm/_logs/2018-09-13T11_38_48_646Z-debug.lo

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained. Please post your issue to https://github.com/OfficeDev/Office-Add-in-samples/issues if you still have questions about any samples.
