### ISSUE TITLE
The AppRead part of the demo doesn't work

### ISSUE THREAD

**Issue by StationaryDave** [OfficeDev/outlook-add-in-command-demo#4]
I was able to set up and use the AppCompose part of the demo with the Outlook 365 web app, and it works nicely, but the AppRead part doesn't work (out of the box, at least).

**Comment by StationaryDave** [comment]
Update:  I was not able to get the icons to display in the ribbon as shown in the ReadMe.  In Outlook 365, when you select an email message and it opens in the right-hand pane, the list of available add-ins for that context may be locked.  A message displays "To help protext your privacy, some content in this message has been blocked. To re-enable the blocked features, click here."  Click and then the title of the add-in is displayed just above the email body.  When you click on the add-in title, a pane expands and the add-in runs.  It might be helpful if the author updates his ReadMe.

**Comment by jasonjoh** [comment]
The icons are only supported in Outlook 2016 on the desktop. In OWA, you would see the standard add-in bar. I see this even for messages that have their content blocked. Is this not what you see?

![capture](https://cloud.githubusercontent.com/assets/8966342/11849671/ff0a2130-a3f6-11e5-89d0-6e10ba7b5d90.PNG)

I can add a screenshot for read mode in OWA to the README if that helps.

**Comment by StationaryDave** [comment]
Thanks! I know it is a challenge when things are changing so fast.
