### ISSUE TITLE
how to remove focus from command-demo-manifest.xml for mac outlook

### ISSUE THREAD

**Issue by chengerchao** [OfficeDev/outlook-add-in-command-demo#42]
Hi:

could you tell me how to remove focus from command-demo-manifest.xml for mac outlook. xml as follows:

  <DisplayName DefaultValue="Add-in Command Demo" />

Thanks.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained. Please post your issue to https://github.com/OfficeDev/Office-Add-in-samples/issues if you still have questions about any samples.
