### ISSUE TITLE
How to consume azure rest api from Outlook Add-In

### ISSUE THREAD

**Issue by srinutamada** [OfficeDev/outlook-add-in-command-demo#43]
I am trying to implement one service which will be hosted in Azure and Outlook Add-In. I have to call custom service that I implemented in Azure from Add-in. Can you provide guidelines or samples which can help in my development?

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained. Please post your issue to https://github.com/OfficeDev/Office-Add-in-samples/issues if you still have questions about any samples.
