### ISSUE TITLE
How to add a new ribbon button like "New Email"?

### ISSUE THREAD

**Issue by allenhiman** [OfficeDev/outlook-add-in-command-demo#44]
i want add a ribbon button like "New Email", and click it show a dialog.
i want add a new menu item insert to "New Items" , and click it show a dialog.
i know it can be done in Visto mode, and how can i do the same thing in the web mode?
Please provide support， thank you.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained. Please post your issue to https://github.com/OfficeDev/Office-Add-in-samples/issues if you still have questions about any samples.
