### ISSUE TITLE
Manifest file doesn't conform to the schema definition

### ISSUE THREAD

**Issue by jmk09** [OfficeDev/outlook-add-in-command-demo#5]
After uploading command-demo-manifest.xml this error message is shown:

> This app can't be installed. The manifest file doesn't conform to the schema definition. The element 'Urls' in namespace 'http://schemas.microsoft.com/office/officeappbasictypes/1.0' cannot contain text. List of possible elements expected: 'Url' in namespace 'http://schemas.microsoft.com/office/officeappbasictypes/1.0'...

**Comment by jmk09** [comment]
Traced the error: [Line 529](https://github.com/jasonjoh/command-demo/blob/master/command-demo-manifest.xml#L529) of the manifest ends with a double quote which shouldn't be there.

``` xml
<bt:Url id="customPaneUrl" DefaultValue="https://localhost:8443/AppRead/CustomPane/CustomPane.html"/>" 
```

**Comment by jasonjoh** [comment]
Thanks for catching that! I'll upload a fix.
