### ISSUE TITLE
How do I show UI not in pane?

### ISSUE THREAD

**Issue by InbarGazit** [OfficeDev/outlook-add-in-command-demo#6]
I understand I can add html/js code that is then called from a Ribbon button and I understand I can use office.js but I'm not clear on how to tie this to Outlook's UI back so that when user clicks the button - they see view inside of Outlook, can someone help with that?

**Comment by jasonjoh** [comment]
I'm not sure what you're looking to do, can you be more specific or include a screenshot? All add-in UI happens in a pane.

**Comment by InbarGazit** [comment]
"All add-in UI happens in a pane" you are 100% sure about this? maybe I'm mistaken but I was told there's another way to show UI. thanks for your help
