### ISSUE TITLE
Duplicated nodes in manifest?

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/outlook-add-in-command-demo#8]
Compare [here](https://github.com/jasonjoh/command-demo/blob/master/command-demo-manifest.xml#L20-L24) and [here](https://github.com/jasonjoh/command-demo/blob/master/command-demo-manifest.xml#L53-L57)

**Comment by iambmelt** [comment]
Compare [here](https://github.com/jasonjoh/command-demo/blob/master/command-demo-manifest.xml#L17-L19) and [here](https://github.com/jasonjoh/command-demo/blob/master/command-demo-manifest.xml#L58-L480)

**Comment by jasonjoh** [comment]
No, the stuff in `VersionOverrides` is for clients that support add-in commands (Outlook 2016), and the stuff before it is for clients that don't yet. Basically the `VersionOverrides` "overrides" the behavior on newer clients :). See https://msdn.microsoft.com/EN-US/library/office/mt267547.aspx

**Comment by iambmelt** [comment]
Thanks for the clarification! 👍
